language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - python --version
  - pip --version
  - uname -a
install:
  - pwd
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=test setup.py test
after_success:
  - coveralls
notifications:
  email: false
